name: Branch Name Suggestion
description: Suggests branch names by looking at the issues properties like milestones and labels.
inputs:
  github-token:
    description: "The GitHub token to be passed to other actions used in this action."
    required: true
runs:
  using: composite
  steps:
    - name: Get the current action version being used
      id: get_action_version
      run: |
        version="${GITHUB_ACTION_REF:-unknown}"
        version="${version#refs/tags/}"
        echo "action_version=$version" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Check for release label
      id: check_release_label
      run: |
        echo "is_release=${{ contains(github.event.issue.labels.*.name, 'release') }}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Generate branch name suggestion
      id: generate_branch_name
      run: |
        if [ "${{ steps.check_release_label.outputs.is_release }}" = "true" ]; then
            branch_name="${{ github.event.issue.milestone.title }}/release"
        else
            branch_name="${{ github.event.issue.milestone.title }}/issue/${{ github.event.issue.number }}"
        fi
        branch_name=$(echo "$branch_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
        echo "Will suggest branch name as: $branch_name"
        echo "suggested_branch_name=$branch_name" >> $GITHUB_OUTPUT
      shell: bash
    - name: Comment on the issue with the suggested branch name
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github-token }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Suggested branch name, generated by the [Branch Name Suggestion](https://github.com/adrianocastro189/ghaction-branch-name-suggestion) action v${{ steps.get_action_version.outputs.action_version }}:

          ```
          ${{ steps.generate_branch_name.outputs.suggested_branch_name }}
          ```
